#Mengambil input
print("Nama Lengkap saya :")
namalengkap=input(" ")
print("Nama panggilan saya :")
namapanggilan=input(" ")
print("Nomor NPM saya :")
npm=int(input())
print("Tempat lahir saya :")
tempatlahir=input("")
print("Umur saya :")
umur=int(input())
print("Alamat saya :")
alamat=input(" ")
print("No HP saya :")
telepon=input()

#Menampilkan output
print("Assalamu'alaiku.")
print(" ")
print("Let me introduce my selt.My name is",namalengkap,", but you can call me",namapanggilan,".")
print("My NPM is",npm,".I was born in",tempatlahir,"and I am",umur, "years old.")
print("I am very glad if you want to invite my house in",alamat,".")
print("So, don't forget to call me before with the number",telepon)
print(" ")
print("Thank you.")
